import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'

import { AuthProvider } from '@/contexts/auth'
import { Toaster } from 'sonner'

import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <AuthProvider>
                <body
                    className={cn(
                        inter.className,
                        'flex flex-col min-h-screen'
                    )}
                >
                    {children}
                    <Toaster />
                </body>
            </AuthProvider>
        </html>
    )
}
